# Generated by Django 5.2.3 on 2025-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the diagram', max_length=255, unique=True)),
                ('elements', models.JSONField(default=list, help_text='Json array of shapes in the diagram')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the diagram was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the diagram was last updated')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
