# Generated by Django 5.2.3 on 2025-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagram',
            options={},
        ),
        migrations.AddField(
            model_name='diagram',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagram',
            name='script',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='elements',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
