# Generated by Django 5.2.3 on 2025-07-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_diagram_options_diagram_metadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagram',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='diagram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the diagram was created'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='elements',
            field=models.JSONField(default=list, help_text='Json array of shapes in the diagram'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='name',
            field=models.CharField(help_text='Name of the diagram', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the diagram was last updated'),
        ),
    ]
