# Generated by Django 5.2.3 on 2025-07-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_diagram_options_remove_diagram_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='elements',
            field=models.JSONField(default=list, help_text='JSON array of shapes in the diagram'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='script',
            field=models.JSONField(blank=True, default=list, help_text='Generated script data for this diagram'),
        ),
    ]
